# Centros Federales

In [1]:
import pandas as pd

In [2]:
población= pd.read_csv('Cuaderno Mensual de Información Estadística Penitenciaria Nacional /2026/poblacion_mensual_detalle.csv')
población.head()

,Mes,Centro,Espacios,Sobrepoblacion_Absoluta,Sobrepoblacion_Relativa_Pct,Fuero_Comun_Subtotal,Fuero_Federal_Subtotal,Poblacion_Total
0,Enero 2026,CEFERESO No. 1 Altiplano,844,-223,-26.42,68,553,621
1,Enero 2026,CEFERESO No. 4 Noroeste,2350,-114,-4.85,1356,880,2236
2,Enero 2026,CEFERESO No. 5 Oriente,3078,-1701,-55.26,764,613,1377
3,Enero 2026,CEFERESO No. 7 Nor-Noroeste,480,-169,-35.21,155,156,311
4,Enero 2026,CEFERESO No. 8 Nor-Poniente,812,-178,-21.92,214,420,634

In [3]:
población.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Mes                          60 non-null     object
 1   Centro                       60 non-null     object
 2   Espacios                     60 non-null     int64
 3   Sobrepoblacion_Absoluta      60 non-null     int64
 4   Sobrepoblacion_Relativa_Pct  60 non-null     float64
 5   Fuero_Comun_Subtotal         60 non-null     int64
 6   Fuero_Federal_Subtotal       60 non-null     int64
 7   Poblacion_Total              60 non-null     int64
dtypes: float64(1), int64(5), object(2)
memory usage: 3.9+ KB

In [4]:
población_promedio= población.groupby('Centro').agg(
    Espacios=('Espacios','first'),
    Promedio_población=('Poblacion_Total', 'mean'),
    Población_min=('Poblacion_Total','min'),
    Población_max=('Poblacion_Total','max'),
    Pct_Sobre_relativa_promedio=('Sobrepoblacion_Relativa_Pct','mean')
).reset_index()
población_promedio

,Centro,Espacios,Promedio_población,Población_min,Población_max,Pct_Sobre_relativa_promedio
0,CEFEREPSI,460,157.25,153,163,-65.8175
1,CEFERESO No. 1 Altiplano,844,615.75,595,628,-27.0425
2,CEFERESO No. 11 CPS Sonora,2520,2261.75,2221,2283,-10.2475
3,CEFERESO No. 12 CPS Guanajuato,2520,2180.00,2161,2197,-13.4950
4,CEFERESO No. 13 CPS Oaxaca,2520,2074.25,2065,2079,-17.6900
5,CEFERESO No. 14 CPS Durango,2520,2258.50,2246,2268,-10.3775
6,CEFERESO No. 15 CPS Chiapas,2520,1775.75,1762,1792,-29.5325
7,CEFERESO No. 16 CPS Femenil Morelos,2528,662.25,651,677,-73.8025
8,CEFERESO No. 17 CPS Michoacán,2520,1969.00,1920,2057,-21.8650
9,CEFERESO No. 18 CPS Coahuila,2528,2010.75,1978,2026,-20.4625
10,CEFERESO No. 4 Noroeste,2350,2243.25,2236,2251,-4.5425
11,CEFERESO No. 5 Oriente,3078,1401.50,1377,1456,-54.4675
12,CEFERESO No. 7 Nor-Noroeste,480,331.25,311,345,-30.9925
13,CEFERESO No. 8 Nor-Poniente,812,717.00,634,767,-11.7000
14,CENTROS PENITENCIARIOS FEDERALES (subtotal),28200,20658.25,20487,20838,-26.7425

In [5]:
población_promedio.loc[:, 'Tipo'] = población_promedio['Centro'].apply(lambda x: 'Privado (CPS)' if 'CPS' in x else 'Publico')

In [6]:
población_promedio = población_promedio[población_promedio['Centro'] != 'CENTROS PENITENCIARIOS FEDERALES (subtotal)']
población_promedio

,Centro,Espacios,Promedio_población,Población_min,Población_max,Pct_Sobre_relativa_promedio,Tipo
0,CEFEREPSI,460,157.25,153,163,-65.8175,Publico
1,CEFERESO No. 1 Altiplano,844,615.75,595,628,-27.0425,Publico
2,CEFERESO No. 11 CPS Sonora,2520,2261.75,2221,2283,-10.2475,Privado (CPS)
3,CEFERESO No. 12 CPS Guanajuato,2520,2180.00,2161,2197,-13.4950,Privado (CPS)
4,CEFERESO No. 13 CPS Oaxaca,2520,2074.25,2065,2079,-17.6900,Privado (CPS)
5,CEFERESO No. 14 CPS Durango,2520,2258.50,2246,2268,-10.3775,Privado (CPS)
6,CEFERESO No. 15 CPS Chiapas,2520,1775.75,1762,1792,-29.5325,Privado (CPS)
7,CEFERESO No. 16 CPS Femenil Morelos,2528,662.25,651,677,-73.8025,Privado (CPS)
8,CEFERESO No. 17 CPS Michoacán,2520,1969.00,1920,2057,-21.8650,Privado (CPS)
9,CEFERESO No. 18 CPS Coahuila,2528,2010.75,1978,2026,-20.4625,Privado (CPS)
10,CEFERESO No. 4 Noroeste,2350,2243.25,2236,2251,-4.5425,Publico
11,CEFERESO No. 5 Oriente,3078,1401.50,1377,1456,-54.4675,Publico
12,CEFERESO No. 7 Nor-Noroeste,480,331.25,311,345,-30.9925,Publico
13,CEFERESO No. 8 Nor-Poniente,812,717.00,634,767,-11.7000,Publico

In [7]:
población_federal = población_promedio.groupby('Tipo').agg(
    n_centros=('Centro','count'), 
    espacios=('Espacios','sum'),
    poblacion_total=('Promedio_población','sum'))
población_federal['porcentaje_ocupación']= población_federal['poblacion_total']/población_federal['espacios']
población_federal= población_federal.reset_index()

In [8]:
incidencias= pd.read_csv('Cuaderno Mensual de Información Estadística Penitenciaria Nacional /2026/incidencias_centros_federales_2026_ancho_compacto.csv')
incidencias

,mes,centro,tipo,incidencia,incidencias,personas_involucradas,personas_heridas
0,2026-01,CEFEREPSI,Publico,Agresiones a Terceros,5.0,5.0,0.0
1,2026-01,CEFERESO No. 1 Altiplano,Publico,Agresiones a Terceros,4.0,4.0,0.0
2,2026-01,CEFERESO No. 14 CPS Durango,Privado (CPS),Agresiones a Terceros,2.0,3.0,0.0
3,2026-01,CEFERESO No. 15 CPS Chiapas,Privado (CPS),Agresiones a Terceros,2.0,17.0,0.0
4,2026-01,CEFERESO No. 17 CPS Michoacan,Privado (CPS),Agresiones a Terceros,7.0,23.0,0.0
...,...,...,...,...,...,...,...
65,2026-04,CEFERESO No. 11 CPS Sonora,Privado (CPS),Riñas,1.0,2.0,0.0
66,2026-04,CEFERESO No. 5 Oriente,Publico,Riñas,1.0,2.0,1.0
67,2026-04,CEFERESO No. 13 CPS Oaxaca,Privado (CPS),Suicidios,1.0,1.0,0.0
68,2026-04,CEFERESO No. 16 CPS Femenil Morelos,Privado (CPS),Suicidios,1.0,1.0,0.0
69,2026-04,CEFERESO No. 18 CPS Coahuila,Privado (CPS),Suicidios,1.0,1.0,0.0

In [9]:
incidencias_federales= incidencias.groupby('tipo').agg(
    n_incidencias=('incidencias','sum'),
    personas_involucradas=('personas_involucradas','sum'), 
    personas_heridas=('personas_heridas','sum'))
incidencias_federales= incidencias_federales.reset_index()

In [10]:
incidencias_federales = incidencias_federales.rename(columns={'tipo': 'Tipo'})

In [11]:
print(población_federal.columns.tolist())
print(incidencias_federales.columns.tolist())

['Tipo', 'n_centros', 'espacios', 'poblacion_total', 'porcentaje_ocupación']
['Tipo', 'n_incidencias', 'personas_involucradas', 'personas_heridas']

In [12]:
federales= pd.merge(población_federal,incidencias_federales, on='Tipo', how='inner')
federales

,Tipo,n_centros,espacios,poblacion_total,porcentaje_ocupación,n_incidencias,personas_involucradas,personas_heridas
0,Privado (CPS),8,20176,15192.25,0.752986,67.0,156.0,20.0
1,Publico,6,8024,5466.00,0.681206,46.0,64.0,4.0

In [13]:
federales ['tasa_incidencia_x1000 ']= federales['n_incidencias']/federales['poblacion_total']*1000
federales

,Tipo,n_centros,espacios,poblacion_total,porcentaje_ocupación,n_incidencias,personas_involucradas,personas_heridas,tasa_incidencia_x1000
0,Privado (CPS),8,20176,15192.25,0.752986,67.0,156.0,20.0,4.410143
1,Publico,6,8024,5466.00,0.681206,46.0,64.0,4.0,8.415660