# Exploracion de datos de la Encuesta Nacional de Población Privada de la Libertad (ENPOL 2021)

In [1]:
# importar todas las paqueterias necesarias 
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd

In [2]:
# son muchos datos y es necesario que las columnas sean visibles 
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
# las columnas a veces traen información muy extensa que es importante ver
pd.set_option('display.max_colwidth', None)

In [4]:
# el diccionario de datos nos permite saber el significado de las columnas
# lo convierto en Data Frame para que sea más fácil de visualizar
#el encoding es por los caracteres especiales del español y la memoria porque es extenso
diccionario= pd.read_csv('datos_enpol24/diccionario_de_datos/diccionario_de_datos_ENPOL2021_2_3.csv', 
                         encoding='latin-1', 
                         low_memory=False
)

In [5]:
# tamaño del data frame
diccionario.shape

(779, 5)

In [6]:
diccionario.head()

,NOMBRE_CAMPO,NEMONICO,TIPO,LONGITUD,RANGO_CLAVES
0,Identificador del informante seleccionado,ID_PER,Numérico,9,0101.0001 3204.026\r
1,Clave de Entidad,CVE_ENT,Alfanumérico,2,01\r
2,Clave de Entidad,CVE_ENT,Alfanumérico,2,02\r
3,Clave de Entidad,CVE_ENT,Alfanumérico,2,03\r
4,Clave de Entidad,CVE_ENT,Alfanumérico,2,04\r

Ahora que tenemos el diccionario de los datos, vamos a convertir todos los datos abiertos de las encuentas en un data frame

In [8]:
# df = Data Frame
df_exploratorio= pd.read_csv('datos_enpol24/conjunto_de_datos/conjunto_de_datos_ENPOL2021_2_3.csv',
    encoding='latin-1',
    low_memory=False
)

In [9]:
# tamaño del data frame
df_exploratorio.shape

(61449, 183)

In [10]:
# imprimo solo las primeras 5 columnas del df porque son muchos datos 
# solo es para darse una idea
df_exploratorio.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
0,101.0001,13,Hidalgo\r,\r,\r,1,1,2,22,1,0,0,0,0,0,0,1,0,0,0,0,0,1,03\r,1,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,"CORTE DE CESPED, ELETRICISTA Y SOLDADOR\r",5299\r,05\r,1\r,\r,\r,1,2,1,1,2,1,2,1,1\r,1,4,4,\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,22,016\r,8,12,2017,13,029\r,17,11,2017,3,3\r,\r,\r,\r,\r,\r,\r,1\r,1\r,1\r,2\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,\r,1\r,1\r,2\r,1\r,1\r,1\r,1\r,2\r,2\r,\r,\r,2\r,2\r,2\r,2\r,1\r,1\r,2\r,1\r,1\r,1\r,2\r,1\r,1\r,2\r,2\r,1\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,01\r,01\r,1\r,2\r,1\r,0\r,0\r,0\r,0\r,0\r,0\r,2\r,\r,1\r,5\r,883.1,3.981132,0.258537
1,101.1432,1,Aguascalientes\r,\r,\r,1,2,2,1,1,0,1,0,0,0,0,1,0,0,0,0,0,1,06\r,1,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,COMERCIANTE\r,4111\r,04\r,1\r,\r,\r,1,1,1,1,2,1,1,2,1\r,3,1,4,\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,1,001\r,3,5,2013,1,001\r,98,4,2012,6,3\r,\r,\r,\r,\r,\r,\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,\r,2\r,2\r,2\r,2\r,2\r,2\r,1\r,2\r,2\r,\r,\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,1\r,2\r,2\r,1\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,01\r,01\r,2\r,2\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,2\r,\r,872.2,1.050000,0.991736
2,101.1477,9,Ciudad de México\r,15\r,RECLUSORIO PREVENTIVO VARONIL ORIENTE\r,1,1,2,9,2,0,0,1,1,0,0,0,0,0,0,0,0,1,03\r,1,1\r,02\r,06\r,1\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,POLICIA MUNICIPAL\r,5312\r,05\r,1\r,\r,\r,1,2,1,1,2,2,1,2,2\r,4,1,9,0\r,1\r,0\r,1\r,0\r,0\r,0\r,0\r,0\r,0\r,9,003\r,25,2,2009,9,003\r,98,10,2007,6,5\r,2\r,\r,\r,\r,\r,\r,1\r,1\r,1\r,1\r,2\r,2\r,1\r,1\r,2\r,2\r,1\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,1\r,1\r,1\r,1\r,1\r,2\r,1\r,2\r,1\r,1\r,1\r,1\r,2\r,1\r,2\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,01\r,04\r,1\r,2\r,1\r,0\r,0\r,0\r,0\r,0\r,0\r,2\r,\r,2\r,\r,210.1,11.704167,0.198020
3,101.2131,32,Zacatecas\r,\r,\r,1,1,2,32,1,0,0,1,1,0,0,0,0,0,0,0,0,2,\r,1,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,CAMPO\r,6119\r,06\r,1\r,\r,\r,1,1,2,1,2,1,2,2,2\r,1,1,4,\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,32,010\r,4,5,2017,32,010\r,98,4,2017,2,4\r,1\r,2\r,1\r,2\r,1\r,2\r,2\r,2\r,1\r,2\r,2\r,2\r,1\r,1\r,2\r,2\r,2\r,\r,1\r,1\r,2\r,1\r,1\r,1\r,2\r,2\r,2\r,\r,\r,2\r,2\r,2\r,2\r,1\r,1\r,1\r,2\r,1\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,01\r,02\r,2\r,2\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,1\r,5\r,2294.1,3.228571,0.416667
4,101.2980,28,Tamaulipas\r,\r,\r,1,1,2,28,3,0,1,0,0,0,0,0,0,0,0,0,0,1,01\r,1,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,2\r,\r,\r,\r,ENCARGADO DE UN CENTRO REHABILITACION\r,5201\r,05\r,1\r,\r,\r,1,2,1,1,2,1,3,2,2\r,1,4,7,\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,28,027\r,29,5,2013,28,027\r,15,5,2013,5,5\r,1\r,\r,\r,\r,\r,\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,\r,\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,2\r,01\r,01\r,2\r,2\r,\r,\r,\r,\r,\r,\r,\r,\r,\r,2\r,\r,1979.1,3.045977,0.368644

## Limpieza de datos

Me dí cuenta que la mayor parte de las columnas tienen este signo '/r' porque la información esta en csv y se separa a partir de cambios de columna. Esto dificulta el análisis de datos, por lo que es necesario limpiarlo

In [11]:
# estoy quitando el '/r' solo a las columnas de texto una columna a la vez
# los reemplaza por vacios y de una vez quita los espacios al principio y al final
df_exploratorio = df_exploratorio.apply(
                lambda col: 
                col.str.replace('\r', '', regex=False).str.strip() 
                      if col.dtype == 'object' else col)

In [12]:
# vemos si quedó bien 
df_exploratorio.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
0,101.0001,13,Hidalgo,,,1,1,2,22,1,0,0,0,0,0,0,1,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,"CORTE DE CESPED, ELETRICISTA Y SOLDADOR",5299,05,1,,,1,2,1,1,2,1,2,1,1,1,4,4,,,,,,,,,,,22,016,8,12,2017,13,029,17,11,2017,3,3,,,,,,,1,1,1,2,2,2,2,1,2,2,2,,1,1,2,1,1,1,1,2,2,,,2,2,2,2,1,1,2,1,1,1,2,1,1,2,2,1,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,01,01,1,2,1,0,0,0,0,0,0,2,,1,5,883.1,3.981132,0.258537
1,101.1432,1,Aguascalientes,,,1,2,2,1,1,0,1,0,0,0,0,1,0,0,0,0,0,1,06,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,COMERCIANTE,4111,04,1,,,1,1,1,1,2,1,1,2,1,3,1,4,,,,,,,,,,,1,001,3,5,2013,1,001,98,4,2012,6,3,,,,,,,2,2,2,2,2,2,2,2,2,2,2,,2,2,2,2,2,2,1,2,2,,,2,2,2,2,2,2,2,2,2,1,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,01,2,2,,,,,,,,,,2,,872.2,1.050000,0.991736
2,101.1477,9,Ciudad de México,15,RECLUSORIO PREVENTIVO VARONIL ORIENTE,1,1,2,9,2,0,0,1,1,0,0,0,0,0,0,0,0,1,03,1,1,02,06,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,POLICIA MUNICIPAL,5312,05,1,,,1,2,1,1,2,2,1,2,2,4,1,9,0,1,0,1,0,0,0,0,0,0,9,003,25,2,2009,9,003,98,10,2007,6,5,2,,,,,,1,1,1,1,2,2,1,1,2,2,1,2,2,2,1,2,2,2,2,2,1,2,2,2,1,1,1,1,1,2,1,2,1,1,1,1,2,1,2,2,2,2,1,2,2,2,1,2,2,2,2,2,2,2,01,04,1,2,1,0,0,0,0,0,0,2,,2,,210.1,11.704167,0.198020
3,101.2131,32,Zacatecas,,,1,1,2,32,1,0,0,1,1,0,0,0,0,0,0,0,0,2,,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,CAMPO,6119,06,1,,,1,1,2,1,2,1,2,2,2,1,1,4,,,,,,,,,,,32,010,4,5,2017,32,010,98,4,2017,2,4,1,2,1,2,1,2,2,2,1,2,2,2,1,1,2,2,2,,1,1,2,1,1,1,2,2,2,,,2,2,2,2,1,1,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,02,2,2,,,,,,,,,,1,5,2294.1,3.228571,0.416667
4,101.2980,28,Tamaulipas,,,1,1,2,28,3,0,1,0,0,0,0,0,0,0,0,0,0,1,01,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,ENCARGADO DE UN CENTRO REHABILITACION,5201,05,1,,,1,2,1,1,2,1,3,2,2,1,4,7,,,,,,,,,,,28,027,29,5,2013,28,027,15,5,2013,5,5,1,,,,,,2,2,2,2,2,2,2,2,2,2,2,,2,2,2,2,2,2,2,2,2,,,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,01,2,2,,,,,,,,,,2,,1979.1,3.045977,0.368644

## Privatización

De acuerdo con los datos del  Informe sobre la situación de las prisiones privadas en México (Documenta y México Evalua, 2021) existen solamente 8 Centros Federales de Reinserción Social (Cefereso) que funcionan bajo la figura de Centro de Prestación de Servicios (CPPS).
Estos son: 
- Cefereso núm. 11 CPS Sonora
- Cefereso núm. 12 CPS Guanajuato
- Cefereso núm. 13 CPS Oaxaca
- Cefereso núm. 14 CPS Durango
- Cefereso núm. 15 CPS Chiapas
- Cefereso núm. 16 CPS Femenil Morelos
- Cefereso núm. 17 CPS Michoacán
- Centro Penitenciario Federal núm. 18 CPS Coahuila

En la encuesta hay muchos datos vacios, por lo que en pirmera instancia es importante separar los datos de fuero federal que contienen los Cefereso

In [13]:
# Revisar si no hay datos vacios en esta columna
df_exploratorio['FUERO'].value_counts()

FUERO
2    55449
1     6000
Name: count, dtype: int64

De acuerdo con el catálogo de esta columna, el número 2 es para centros estatales o municipales y el 1 para federales

In [14]:
# Nuevo df donde solo existan los datos de centros federales 
df_federal=df_exploratorio[df_exploratorio['FUERO']==1].copy()
df_federal.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
11,101.4995,10,Durango,,,1,1,1,10,1,0,0,1,1,0,0,0,0,0,0,0,0,2,,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,OBRERO,7999,07,2,,04,2,2,2,2,2,1,2,2,2,6,1,1,,,,,,,,,,,10,017,15,7,2006,10,017,15,7,2006,1,2,,,,,,,1,2,1,2,2,2,2,2,2,2,2,,2,2,1,1,2,2,1,2,2,,,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,03,04,2,2,,,,,,,,,,2,,3037.1,5.425532,0.184314
24,102.0023,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,1,04,01,2,2,,,,2,,,,2,,,,SICARIO,1012,10,1,,,1,2,1,2,1,1,1,1,1,6,1,7,,,,,,,,,,,8,019,10,3,2011,8,019,10,3,2011,1,5,1,,,,,,2,2,2,2,2,2,1,2,2,2,2,,2,1,1,2,2,2,1,2,1,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,03,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
27,102.0958,18,Nayarit,38,CEFERESO 4 NOROESTE,1,1,1,98,2,1,0,0,0,0,0,0,0,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,VENTA DE DROGA,1014,10,1,,,1,2,1,2,1,1,1,1,1,6,1,15,,,,,,,,,,,98,,2,12,2015,97,,20,6,2015,5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1211.1,1.626005,0.598716
28,102.1081,18,Nayarit,38,CEFERESO 4 NOROESTE,1,1,1,9,1,0,0,0,0,0,0,0,1,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,TRABAJABA EN LA CONSTRUCCION,7121,07,1,,,1,2,1,2,1,1,3,1,1,4,4,5,,,,,,,,,,,9,007,31,1,2015,15,031,9,1,2015,3,5,1,,,,,,2,1,1,1,2,2,1,1,2,2,2,,2,2,2,2,2,2,2,2,2,,,2,2,2,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,1,2,2,2,1,2,2,2,2,2,2,2,06,06,1,1,1,0,0,1,0,0,0,2,,1,5,1211.1,1.626005,0.598716
36,102.4876,30,Veracruz de Ignacio de la Llave,52,CEFERESO 5 ORIENTE,1,1,1,28,2,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,DJ DE UN CENTRO NOCTURNO E INSTALADOR DE CAMARAS DE CIRCUITO CERRADO EQUIPO DE LUCES AUDIO Y SONIDO,2654,02,1,,,1,2,1,1,2,1,1,2,2,4,4,7,,,,,,,,,,,28,022,20,9,2018,28,022,20,9,2018,1,5,1,,,,,,1,1,1,1,2,2,1,2,2,2,2,,2,2,1,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,2,1,1,1,1,2,2,2,2,1,2,1,1,2,2,1,2,2,2,2,1,2,2,01,04,2,2,,,,,,,,,,1,5,394.1,2.190865,0.581043

In [15]:
# conteo de con cuantos datos estamos trabajando
df_federal.shape

(6000, 183)

Ahora, sabemos los estados donde se encuentran los centros que funcionan bajo la figura del CPS

In [16]:
# nuevo df con los estados que queremos 
estados_cps = ['Oaxaca','Sonora', 'Guanajuato', 'Durango', 'Chiapas', 'Morelos', 'Michoacán de Ocampo', 'Coahuila de Zaragoza']
df_estados=df_federal[df_federal['NOM_ENT'].isin(estados_cps)].copy()
df_estados.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
11,101.4995,10,Durango,,,1,1,1,10,1,0,0,1,1,0,0,0,0,0,0,0,0,2,,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,OBRERO,7999,07,2,,04,2,2,2,2,2,1,2,2,2,6,1,1,,,,,,,,,,,10,017,15,7,2006,10,017,15,7,2006,1,2,,,,,,,1,2,1,2,2,2,2,2,2,2,2,,2,2,1,1,2,2,1,2,2,,,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,03,04,2,2,,,,,,,,,,2,,3037.1,5.425532,0.184314
24,102.0023,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,1,04,01,2,2,,,,2,,,,2,,,,SICARIO,1012,10,1,,,1,2,1,2,1,1,1,1,1,6,1,7,,,,,,,,,,,8,019,10,3,2011,8,019,10,3,2011,1,5,1,,,,,,2,2,2,2,2,2,1,2,2,2,2,,2,1,1,2,2,2,1,2,1,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,03,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
95,105.1315,5,Coahuila de Zaragoza,08,"CENTRO PENITENCIARIO FEDERAL 18 ""CPS COAHUILA""",1,1,1,8,1,0,1,0,0,0,0,0,0,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,PINTOR DE CASAS,7135,07,1,,,1,2,1,1,1,1,1,1,1,4,1,1,,,,,,,,,,,8,037,98,98,2020,8,037,12,8,2020,1,5,2,,,,,,1,1,1,2,2,2,1,2,2,2,2,,2,2,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,03,06,2,2,,,,,,,,,,1,5,1897.1,3.121368,0.330695
98,105.3041,26,Sonora,49,CEFERESO 11 CPS SONORA,1,1,1,27,1,0,1,0,0,0,0,1,0,0,0,0,0,1,03,1,1,06,00,2,2,,,,2,,,,2,,,,2,,,,2,,,,1,10,00,2,2,,,,2,,,,2,,,,COMERCIANTE,4111,04,1,,,1,1,2,1,2,1,1,2,2,6,1,1,,,,,,,,,,,27,010,16,3,2020,27,010,16,3,2020,1,1,,,,,,,1,1,1,2,2,2,1,2,2,2,2,,1,2,1,1,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,03,2,2,,,,,,,,,,2,,2346.1,3.242424,0.307655
100,105.4540,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,21,2,0,1,0,0,0,0,0,1,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,D.J. ANIMADOR DE EVENTOS SOCIALES.,2654,02,1,,,1,1,1,2,1,1,1,1,1,6,4,4,,,,,,,,,,,21,132,6,4,2014,21,114,5,4,2014,2,5,1,,,,,,2,1,1,2,2,2,1,1,1,2,2,,2,2,2,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,1,2,1,2,1,2,1,1,1,1,1,1,2,1,1,2,2,2,1,1,2,2,03,07,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515

In [17]:
# Ahora hay que ver que centros federeales se encuentran en los estados
for ent, grupo in df_estados.groupby('NOM_ENT'):
    print(f"\n{ent}:")
    print(grupo['NOM_INT'].unique())

Chiapas:
['']

Coahuila de Zaragoza:
['CENTRO PENITENCIARIO FEDERAL 18 "CPS COAHUILA"']

Durango:
['' 'CEFERESO 14 CPS DURANGO']

Guanajuato:
['CEFERESO 12 CPS GUANAJUATO']

Michoacán de Ocampo:
['']

Morelos:
['CEFERESO 16 CPS MORELOS' '']

Oaxaca:
['CEFERESO 13 CPS OAXACA']

Sonora:
['CEFERESO 11 CPS SONORA']

Hay datos vacios en Chiapas, Durango, Michoacán y Morelos. De acuerdo con los datos del [Observatorio de Prisiones](https://observatorio-de-prisiones.documenta.org.mx/category/centros-penitenciarios/) solo existe un centro federal en Chiapas y Michoacán, sin embargo en Morelos existe el Centro Federal de Rehabilitación Psicosocial (CEFERPSI) y en Durango el CEFERESO No 7. Nor-Noroeste Durango.

In [18]:
# Para asegurarnos que no esten en los datos originales checamos los valores 
df_exploratorio['NOM_INT'].unique()

array(['', 'RECLUSORIO PREVENTIVO VARONIL ORIENTE',
       'CERESO CHALCO MIXQUIC', 'COMISARIA DE REINSERCION FEMENIL',
       'RECLUSORIO PREVENTIVO VARONIL NORTE', 'CERESO ACAPULCO DE JUAREZ',
       'CERESO VILLAHERMOSA', 'CERESO MERIDA', 'CERESO ESTATAL NO.1',
       'CERESO NAYARIT', 'CERESO TIJUANA', 'CEFERESO 14 CPS DURANGO',
       'CERESO NEZAHUALCOYOTL BORDO', 'CEFERESO 4 NOROESTE',
       'CERESO AGUASCALIENTES', 'CEFERESO 5 ORIENTE', 'CERESO DURANGO',
       'CEFERESO 1 ALTIPLANO', 'PENITENCIARIA SAN LUIS POTOSI',
       'CERESO KOBEN', 'CERESO MORELOS VARONIL',
       'CENTRO FEMENIL DE REINSERCIÓN SOCIAL SANTA MARTHA ACATITLA',
       'CERESO PUEBLA', 'RECLUSORIO PREVENTIVO VARONIL SUR',
       'CEPRERESO LEON', 'CERESO ALMOLOYA SANTIAGUITO',
       'CERESO HERMOSILLO I', 'CERESO ECATEPEC DR. SERGIO GARCIA RAMIREZ',
       'CERESO EL HONGO', 'CEFERESO NO 8 NOR-PONIENTE',
       'CERESO TEXCOCO DR. ALFONSO QUIROZ CUARON', 'CERESO MEXICALI',
       'CERESO CUAUTITLAN',
       'CENTRO PENITENCIARIO FEDERAL 18 "CPS COAHUILA"',
       'COMISARIA DE REINSERCION SOCIAL', 'CEFERESO 11 CPS SONORA',
       'CERESO NUM. 14 CINTALAPA (EL AMATE)', 'CERESO ESTATAL NO.3',
       'CERESO HONGO II', 'PENITENCIARIA DE LA CIUDAD DE MÉXICO',
       'CEFERESO 12 CPS GUANAJUATO', 'CERESO DE MEDIA SEGURIDAD TANIVET',
       'COMISARIA DE PRISION PREVENTIVA', 'CERESO ENSENADA',
       'CERESO SAN JOSE EL ALTO', 'CERESO COLIMA',
       'CERESO TLALNEPANTLA JUAN FERNANDEZ ALBARRAN',
       'CEFERESO 16 CPS MORELOS', 'CERESO PACHUCA',
       'CERESO DUPONT OSTION COATZACOALCOS', 'CERESO CIENEGUILLAS',
       'CENTRO DE REINSERCIÓN SOCIAL NÚMERO 1', 'CEFERESO 13 CPS OAXACA',
       'CENTRO DE REINSERCIÓN SOCIAL FEMENIL',
       'CENTRO DE REINSERCIÓN SOCIAL NÚMERO 3'], dtype=object)

No existe en los nombres de los centros, por lo que es posible asumir que pueden ser los dats que faltan. Es por eso que vamos a excluirlos del df

In [21]:
# Checar si la condición se construyo bien 
condicion_vacia_D = (df_estados['NOM_ENT'] == 'Durango') & (df_estados['NOM_INT']== '')
condicion_vacia_D.value_counts()

False    4057
True       47
Name: count, dtype: int64

In [22]:
#Establecemos una condición y la aplicamos al df para Durango
df_estados= df_estados[~condicion_vacia_D]
df_estados.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
24,102.0023,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,1,04,01,2,2,,,,2,,,,2,,,,SICARIO,1012,10,1,,,1,2,1,2,1,1,1,1,1,6,1,7,,,,,,,,,,,8,019,10,3,2011,8,019,10,3,2011,1,5,1,,,,,,2,2,2,2,2,2,1,2,2,2,2,,2,1,1,2,2,2,1,2,1,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,03,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
95,105.1315,5,Coahuila de Zaragoza,08,"CENTRO PENITENCIARIO FEDERAL 18 ""CPS COAHUILA""",1,1,1,8,1,0,1,0,0,0,0,0,0,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,PINTOR DE CASAS,7135,07,1,,,1,2,1,1,1,1,1,1,1,4,1,1,,,,,,,,,,,8,037,98,98,2020,8,037,12,8,2020,1,5,2,,,,,,1,1,1,2,2,2,1,2,2,2,2,,2,2,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,03,06,2,2,,,,,,,,,,1,5,1897.1,3.121368,0.330695
98,105.3041,26,Sonora,49,CEFERESO 11 CPS SONORA,1,1,1,27,1,0,1,0,0,0,0,1,0,0,0,0,0,1,03,1,1,06,00,2,2,,,,2,,,,2,,,,2,,,,2,,,,1,10,00,2,2,,,,2,,,,2,,,,COMERCIANTE,4111,04,1,,,1,1,2,1,2,1,1,2,2,6,1,1,,,,,,,,,,,27,010,16,3,2020,27,010,16,3,2020,1,1,,,,,,,1,1,1,2,2,2,1,2,2,2,2,,1,2,1,1,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,03,2,2,,,,,,,,,,2,,2346.1,3.242424,0.307655
100,105.4540,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,21,2,0,1,0,0,0,0,0,1,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,D.J. ANIMADOR DE EVENTOS SOCIALES.,2654,02,1,,,1,1,1,2,1,1,1,1,1,6,4,4,,,,,,,,,,,21,132,6,4,2014,21,114,5,4,2014,2,5,1,,,,,,2,1,1,2,2,2,1,1,1,2,2,,2,2,2,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,1,2,1,2,1,2,1,1,1,1,1,1,2,1,1,2,2,2,1,1,2,2,03,07,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
130,107.0236,11,Guanajuato,21,CEFERESO 12 CPS GUANAJUATO,1,1,1,11,1,0,1,0,0,0,0,1,0,0,0,0,0,1,04,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,AYUDANTE DE ALBANIL,9221,09,1,,,1,2,2,2,2,2,1,1,2,3,4,2,,,,,,,,,,,11,009,5,12,2020,11,009,98,8,2019,6,3,,,,,,,1,2,1,2,1,2,1,1,2,2,2,,2,2,1,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,2,2,1,1,2,1,1,1,1,2,1,1,2,1,2,2,2,2,2,1,2,2,03,05,1,2,1,0,0,0,0,0,0,2,,1,4,1891.1,2.971256,0.335874

In [23]:
condicion_vacia_M = (df_estados['NOM_ENT'] == 'Morelos') & (df_estados['NOM_INT']== '')
condicion_vacia_M.value_counts()

False    4051
True        6
Name: count, dtype: int64

In [24]:
#Establecemos una condición y la aplicamos al df para Morelos
df_estados= df_estados[~condicion_vacia_M]
df_estados.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
24,102.0023,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,1,04,01,2,2,,,,2,,,,2,,,,SICARIO,1012,10,1,,,1,2,1,2,1,1,1,1,1,6,1,7,,,,,,,,,,,8,019,10,3,2011,8,019,10,3,2011,1,5,1,,,,,,2,2,2,2,2,2,1,2,2,2,2,,2,1,1,2,2,2,1,2,1,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,03,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
95,105.1315,5,Coahuila de Zaragoza,08,"CENTRO PENITENCIARIO FEDERAL 18 ""CPS COAHUILA""",1,1,1,8,1,0,1,0,0,0,0,0,0,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,PINTOR DE CASAS,7135,07,1,,,1,2,1,1,1,1,1,1,1,4,1,1,,,,,,,,,,,8,037,98,98,2020,8,037,12,8,2020,1,5,2,,,,,,1,1,1,2,2,2,1,2,2,2,2,,2,2,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,03,06,2,2,,,,,,,,,,1,5,1897.1,3.121368,0.330695
98,105.3041,26,Sonora,49,CEFERESO 11 CPS SONORA,1,1,1,27,1,0,1,0,0,0,0,1,0,0,0,0,0,1,03,1,1,06,00,2,2,,,,2,,,,2,,,,2,,,,2,,,,1,10,00,2,2,,,,2,,,,2,,,,COMERCIANTE,4111,04,1,,,1,1,2,1,2,1,1,2,2,6,1,1,,,,,,,,,,,27,010,16,3,2020,27,010,16,3,2020,1,1,,,,,,,1,1,1,2,2,2,1,2,2,2,2,,1,2,1,1,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,03,2,2,,,,,,,,,,2,,2346.1,3.242424,0.307655
100,105.4540,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,21,2,0,1,0,0,0,0,0,1,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,D.J. ANIMADOR DE EVENTOS SOCIALES.,2654,02,1,,,1,1,1,2,1,1,1,1,1,6,4,4,,,,,,,,,,,21,132,6,4,2014,21,114,5,4,2014,2,5,1,,,,,,2,1,1,2,2,2,1,1,1,2,2,,2,2,2,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,1,2,1,2,1,2,1,1,1,1,1,1,2,1,1,2,2,2,1,1,2,2,03,07,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
130,107.0236,11,Guanajuato,21,CEFERESO 12 CPS GUANAJUATO,1,1,1,11,1,0,1,0,0,0,0,1,0,0,0,0,0,1,04,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,AYUDANTE DE ALBANIL,9221,09,1,,,1,2,2,2,2,2,1,1,2,3,4,2,,,,,,,,,,,11,009,5,12,2020,11,009,98,8,2019,6,3,,,,,,,1,2,1,2,1,2,1,1,2,2,2,,2,2,1,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,2,2,1,1,2,1,1,1,1,2,1,1,2,1,2,2,2,2,2,1,2,2,03,05,1,2,1,0,0,0,0,0,0,2,,1,4,1891.1,2.971256,0.335874

Como para Chiapas y Michoacan solo hay un solo centro federal, podemos asumir que estan hablando del CEFERESO No. 15 CPS Chiapas y el CEFERESO No. 17 CPS Michoacán  por lo que vamos a añadir esta información

In [25]:
condicion_vacia_C = (df_estados['NOM_ENT'] == 'Chiapas') & (df_estados['NOM_INT']== '')
condicion_vacia_C.value_counts()

False    3974
True       77
Name: count, dtype: int64

In [26]:
df_estados.loc[condicion_vacia_C, 'NOM_INT'] = 'CEFERESO 15 CPS CHIAPAS'
df_estados.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
24,102.0023,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,1,04,01,2,2,,,,2,,,,2,,,,SICARIO,1012,10,1,,,1,2,1,2,1,1,1,1,1,6,1,7,,,,,,,,,,,8,019,10,3,2011,8,019,10,3,2011,1,5,1,,,,,,2,2,2,2,2,2,1,2,2,2,2,,2,1,1,2,2,2,1,2,1,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,03,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
95,105.1315,5,Coahuila de Zaragoza,08,"CENTRO PENITENCIARIO FEDERAL 18 ""CPS COAHUILA""",1,1,1,8,1,0,1,0,0,0,0,0,0,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,PINTOR DE CASAS,7135,07,1,,,1,2,1,1,1,1,1,1,1,4,1,1,,,,,,,,,,,8,037,98,98,2020,8,037,12,8,2020,1,5,2,,,,,,1,1,1,2,2,2,1,2,2,2,2,,2,2,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,03,06,2,2,,,,,,,,,,1,5,1897.1,3.121368,0.330695
98,105.3041,26,Sonora,49,CEFERESO 11 CPS SONORA,1,1,1,27,1,0,1,0,0,0,0,1,0,0,0,0,0,1,03,1,1,06,00,2,2,,,,2,,,,2,,,,2,,,,2,,,,1,10,00,2,2,,,,2,,,,2,,,,COMERCIANTE,4111,04,1,,,1,1,2,1,2,1,1,2,2,6,1,1,,,,,,,,,,,27,010,16,3,2020,27,010,16,3,2020,1,1,,,,,,,1,1,1,2,2,2,1,2,2,2,2,,1,2,1,1,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,03,2,2,,,,,,,,,,2,,2346.1,3.242424,0.307655
100,105.4540,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,21,2,0,1,0,0,0,0,0,1,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,D.J. ANIMADOR DE EVENTOS SOCIALES.,2654,02,1,,,1,1,1,2,1,1,1,1,1,6,4,4,,,,,,,,,,,21,132,6,4,2014,21,114,5,4,2014,2,5,1,,,,,,2,1,1,2,2,2,1,1,1,2,2,,2,2,2,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,1,2,1,2,1,2,1,1,1,1,1,1,2,1,1,2,2,2,1,1,2,2,03,07,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
130,107.0236,11,Guanajuato,21,CEFERESO 12 CPS GUANAJUATO,1,1,1,11,1,0,1,0,0,0,0,1,0,0,0,0,0,1,04,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,AYUDANTE DE ALBANIL,9221,09,1,,,1,2,2,2,2,2,1,1,2,3,4,2,,,,,,,,,,,11,009,5,12,2020,11,009,98,8,2019,6,3,,,,,,,1,2,1,2,1,2,1,1,2,2,2,,2,2,1,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,2,2,1,1,2,1,1,1,1,2,1,1,2,1,2,2,2,2,2,1,2,2,03,05,1,2,1,0,0,0,0,0,0,2,,1,4,1891.1,2.971256,0.335874

In [27]:
condicion_vacia_M = (df_estados['NOM_ENT'] == 'Michoacán de Ocampo') & (df_estados['NOM_INT']== '')
condicion_vacia_M.value_counts()

False    3998
True       53
Name: count, dtype: int64

In [28]:
df_estados.loc[condicion_vacia_M, 'NOM_INT'] = 'CEFERESO No. 17 CPS Michoacán'
df_estados.head()

,ID_PER,CVE_ENT,NOM_ENT,CEN_INT,NOM_INT,COD_RES,SEXO,FUERO,P2_1,P2_2,P2_3_01,P2_3_02,P2_3_03,P2_3_04,P2_3_05,P2_3_06,P2_3_07,P2_3_08,P2_3_09,P2_3_10,P2_3_98,P2_3_99,P2_4,P2_5,P2_6,P2_7_1,P2_8A_1,P2_8M_1,P2_9_1,P2_7_2,P2_8A_2,P2_8M_2,P2_9_2,P2_7_3,P2_8A_3,P2_8M_3,P2_9_3,P2_7_4,P2_8A_4,P2_8M_4,P2_9_4,P2_7_5,P2_8A_5,P2_8M_5,P2_9_5,P2_7_6,P2_8A_6,P2_8M_6,P2_9_6,P2_7_7,P2_8A_7,P2_8M_7,P2_9_7,P2_7_8,P2_8A_8,P2_8M_8,P2_9_8,P2_7_9,P2_8A_9,P2_8M_9,P2_9_9,P2_7_10,P2_8A_10,P2_8M_10,P2_9_10,P2_10_E,R2_10_CVE,R2_10_X,P2_11,P2_12,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15,P3_1,P3_2,P3_2A_01,P3_2A_02,P3_2A_03,P3_2A_04,P3_2A_05,P3_2A_06,P3_2A_07,P3_2A_08,P3_2A_98,P3_2A_99,P3_3,P3_4,P3_5_D,P3_5_M,P3_5_A,P3_6,P3_7,P3_8_D,P3_8_M,P3_8_A,P3_9,P3_10,P3_11,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P3_13_01,P3_13_02,P3_13_03,P3_13_04,P3_13_05,P3_13_06,P3_13_07,P3_13_08,P3_13_09,P3_13_10,P3_13_11,P3_13_12,P3_14_1,P3_14_2,P3_14_3,P3_14_4,P3_14_5,P3_14_6,P3_15_1,P3_15_2,P3_15_3,P3_15_4,P3_15_5,P3_15_6,P3_15_7,P3_15_8,P3_15_9,P3_16,P3_17_01,P3_17_02,P3_17_03,P3_17_04,P3_17_05,P3_17_06,P3_17_07,P3_17_08,P3_17_09,P3_17_10,P3_17_11,P3_18_01,P3_18_02,P3_18_03,P3_18_04,P3_18_05,P3_18_06,P3_18_07,P3_18_08,P3_18_09,P3_18_10,P3_18_11,P3_18_12,P3_18_13,P3_18_14,P3_18_15,P3_19,P3_20,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,EST_DIS,FAC_PER,FPC
24,102.0023,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,1,04,01,2,2,,,,2,,,,2,,,,SICARIO,1012,10,1,,,1,2,1,2,1,1,1,1,1,6,1,7,,,,,,,,,,,8,019,10,3,2011,8,019,10,3,2011,1,5,1,,,,,,2,2,2,2,2,2,1,2,2,2,2,,2,1,1,2,2,2,1,2,1,2,2,2,2,2,2,1,2,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,11,03,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
95,105.1315,5,Coahuila de Zaragoza,08,"CENTRO PENITENCIARIO FEDERAL 18 ""CPS COAHUILA""",1,1,1,8,1,0,1,0,0,0,0,0,0,0,0,0,0,1,02,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,PINTOR DE CASAS,7135,07,1,,,1,2,1,1,1,1,1,1,1,4,1,1,,,,,,,,,,,8,037,98,98,2020,8,037,12,8,2020,1,5,2,,,,,,1,1,1,2,2,2,1,2,2,2,2,,2,2,1,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,1,1,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,03,06,2,2,,,,,,,,,,1,5,1897.1,3.121368,0.330695
98,105.3041,26,Sonora,49,CEFERESO 11 CPS SONORA,1,1,1,27,1,0,1,0,0,0,0,1,0,0,0,0,0,1,03,1,1,06,00,2,2,,,,2,,,,2,,,,2,,,,2,,,,1,10,00,2,2,,,,2,,,,2,,,,COMERCIANTE,4111,04,1,,,1,1,2,1,2,1,1,2,2,6,1,1,,,,,,,,,,,27,010,16,3,2020,27,010,16,3,2020,1,1,,,,,,,1,1,1,2,2,2,1,2,2,2,2,,1,2,1,1,1,2,1,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,01,03,2,2,,,,,,,,,,2,,2346.1,3.242424,0.307655
100,105.4540,10,Durango,19,CEFERESO 14 CPS DURANGO,1,1,1,21,2,0,1,0,0,0,0,0,1,0,0,0,0,1,03,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,D.J. ANIMADOR DE EVENTOS SOCIALES.,2654,02,1,,,1,1,1,2,1,1,1,1,1,6,4,4,,,,,,,,,,,21,132,6,4,2014,21,114,5,4,2014,2,5,1,,,,,,2,1,1,2,2,2,1,1,1,2,2,,2,2,2,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,1,2,1,2,1,2,1,1,1,1,1,1,2,1,1,2,2,2,1,1,2,2,03,07,2,2,,,,,,,,,,1,5,767.1,2.676671,0.371515
130,107.0236,11,Guanajuato,21,CEFERESO 12 CPS GUANAJUATO,1,1,1,11,1,0,1,0,0,0,0,1,0,0,0,0,0,1,04,1,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,2,,,,AYUDANTE DE ALBANIL,9221,09,1,,,1,2,2,2,2,2,1,1,2,3,4,2,,,,,,,,,,,11,009,5,12,2020,11,009,98,8,2019,6,3,,,,,,,1,2,1,2,1,2,1,1,2,2,2,,2,2,1,2,2,2,1,2,2,,,2,2,2,2,1,1,1,1,1,2,2,1,1,2,1,1,1,1,2,1,1,2,1,2,2,2,2,2,1,2,2,03,05,1,2,1,0,0,0,0,0,0,2,,1,4,1891.1,2.971256,0.335874

In [29]:
#estos son los datos disponibles en esta encuesta para prisiones privadas
df_estados.shape

(4051, 183)

## Datos para la visualización

Para saber que datos nos sirven, regresemos al diccionario

In [30]:
diccionario.head()

,NOMBRE_CAMPO,NEMONICO,TIPO,LONGITUD,RANGO_CLAVES
0,Identificador del informante seleccionado,ID_PER,Numérico,9,0101.0001 3204.026\r
1,Clave de Entidad,CVE_ENT,Alfanumérico,2,01\r
2,Clave de Entidad,CVE_ENT,Alfanumérico,2,02\r
3,Clave de Entidad,CVE_ENT,Alfanumérico,2,03\r
4,Clave de Entidad,CVE_ENT,Alfanumérico,2,04\r

Para el perfil de la población es relevante el identificador de la personas selccionada por si queremos cruzar información particular, el nombre del estado y el nombre del centro penitenciario de interés:

In [31]:
perfil_poblacion=['ID_PER','SEXO', 'NOM_ENT','NOM_INT']

Para saber la situación socioeconómica de las personas: Principal fuente de ingresos la semana previa a su detención, Situación en el hogar el año previo a su detención: suficiencia alimentaria,  existencia de deudas, suficiencia monetaria para ropa y calzado, suficiencia monetaria para actividades de ocio,  suficiencia monetaria para medicinas o atención médica en caso de ser requeridas, Situación en el hogar el año previo a su detención: capacidad de ahorro  y Rango de ingreso que tuvo el mes previo a su detención

In [32]:
perfil_socioeconomico=['P2_13', 'P2_14_1', 'P2_14_2','P2_14_2', 'P2_14_3','P2_14_4','P2_14_5','P2_14_6','P2_14_7',
                       'P2_14_8','P2_14_9','P2_15']

Para saber la situación jurídica, es importante conocer la entidad en que vivía antes de la detención, Razón de la reclusión, autoridades que le detuvieron, Entidad federativa de detención, año de detención, Entidad federativa en que ocurrió el delito por el que se le acusa,Año de ocurrencia del delito, Situación del detención

In [33]:
situacion_juridica=['P2_1','P3_1','P3_2','P3_3', 'P3_5_A','P3_6', 'P3_8_A', 'P3_10',]

Para las situaciones de corrupción las variables importantes son: Corrupción en la detención: Solicitud directa, Corrupción en la detención: Insinuación o generación de condiciones, Beneficio que se obtendría del acto de cohecho: Dejarle ir, Beneficio que se obtendría del acto de cohecho: No agredirle, Beneficio que se obtendría del acto de cohecho: No hacerle daño a su familia o amigos, Beneficio que se obtendría del acto de cohecho: Modificar la versión de los hechos o la evidencia en su contra, Beneficio que se obtendría del acto de cohecho: Otra, Beneficio que se obtendría del acto de cohecho: No sabe, Beneficio que se obtendría del acto de cohecho: No responde, Consumación del cohecho, Monto erogado por corrupción durante la detención, Robo por parte de las autoridades al momento de la detención Y Cantidad aproximada de dinero que la autoridad encargada de la detención le robó

In [34]:
corrupcion=['P3_21_1', 'P3_21_2','P3_22_1', 'P3_22_2','P3_22_3','P3_22_4','P3_22_5','P3_22_8','P3_22_9','P3_23', 'P3_24','P3_25', 'P3_26']

Para temas de violencia y tortura: Inspección al cuerpo o pertenencias: le desvistieron,  le informaron qué buscaban,autoridad encontró lo que buscaba o algún objeto ilegal, le sembraron algún objeto,  videograbación de la inspección

In [35]:
violencia_tortura=['P3_12_1','P3_12_2','P3_12_3','P3_12_4','P3_12_5']

In [36]:
# Columnas que conformaran el df de visualización
columnas=list(dict.fromkeys(
    perfil_poblacion +
    situacion_juridica +
    corrupcion +
    violencia_tortura +
    perfil_socioeconomico)
    )

In [37]:
datos_visualización=df_estados[columnas].copy()

In [38]:
#los datos con los que se trabaja la visualización
datos_visualización.shape

(4051, 41)

In [39]:
datos_visualización.head()

,ID_PER,SEXO,NOM_ENT,NOM_INT,P2_1,P3_1,P3_2,P3_3,P3_5_A,P3_6,P3_8_A,P3_10,P3_21_1,P3_21_2,P3_22_1,P3_22_2,P3_22_3,P3_22_4,P3_22_5,P3_22_8,P3_22_9,P3_23,P3_24,P3_25,P3_26,P3_12_1,P3_12_2,P3_12_3,P3_12_4,P3_12_5,P2_13,P2_14_1,P2_14_2,P2_14_3,P2_14_4,P2_14_5,P2_14_6,P2_14_7,P2_14_8,P2_14_9,P2_15
24,102.0023,1,Durango,CEFERESO 14 CPS DURANGO,8,1,7,8,2011,8,2011,5,2,2,,,,,,,,,,1,5,,,,,,,1,2,1,2,1,1,1,1,1,6
95,105.1315,1,Coahuila de Zaragoza,"CENTRO PENITENCIARIO FEDERAL 18 ""CPS COAHUILA""",8,1,1,8,2020,8,2020,5,2,2,,,,,,,,,,1,5,,,,,,,1,2,1,1,1,1,1,1,1,4
98,105.3041,1,Sonora,CEFERESO 11 CPS SONORA,27,1,1,27,2020,27,2020,1,2,2,,,,,,,,,,2,,,,,,,,1,1,2,1,2,1,1,2,2,6
100,105.4540,1,Durango,CEFERESO 14 CPS DURANGO,21,4,4,21,2014,21,2014,5,2,2,,,,,,,,,,1,5,,,,,,,1,1,1,2,1,1,1,1,1,6
130,107.0236,1,Guanajuato,CEFERESO 12 CPS GUANAJUATO,11,4,2,11,2020,11,2019,3,1,2,1,0,0,0,0,0,0,2,,1,4,,,,,,,1,2,2,2,2,2,1,1,2,3

## Visualización

In [40]:
datos_visualización['NOM_INT'].value_counts()

NOM_INT
CEFERESO 16 CPS MORELOS                           756
CEFERESO 14 CPS DURANGO                           733
CEFERESO 12 CPS GUANAJUATO                        661
CEFERESO 11 CPS SONORA                            627
CENTRO PENITENCIARIO FEDERAL 18 "CPS COAHUILA"    585
CEFERESO 13 CPS OAXACA                            559
CEFERESO 15 CPS CHIAPAS                            77
CEFERESO No. 17 CPS Michoacán                      53
Name: count, dtype: int64

El primer paso es hacer un mapa de donde se situan los centros privados, para eso necesitamos solo las columnas NOM_ENT	y NOM_INT

In [44]:
Datos_mapa= datos_visualización[['NOM_ENT', 'NOM_INT']].drop_duplicates()
Datos_mapa

                   NOM_ENT                                         NOM_INT
24                 Durango                         CEFERESO 14 CPS DURANGO
95    Coahuila de Zaragoza  CENTRO PENITENCIARIO FEDERAL 18 "CPS COAHUILA"
98                  Sonora                          CEFERESO 11 CPS SONORA
130             Guanajuato                      CEFERESO 12 CPS GUANAJUATO
176                Morelos                         CEFERESO 16 CPS MORELOS
257                 Oaxaca                          CEFERESO 13 CPS OAXACA
918    Michoacán de Ocampo                   CEFERESO No. 17 CPS Michoacán
1082               Chiapas                         CEFERESO 15 CPS CHIAPAS

Hay que descargar el mapa en un formao Geojson y convertir la información en un geo data frame=gdf